// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
)

func (l *Launchpad) Project(ctx context.Context) (*Project, error) {
	result, err := l.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = l.QueryProject().Only(ctx)
	}
	return result, err
}

func (m *Mint) Project(ctx context.Context) (*Project, error) {
	result, err := m.Edges.ProjectOrErr()
	if IsNotLoaded(err) {
		result, err = m.QueryProject().Only(ctx)
	}
	return result, err
}

func (pr *Project) Mint(ctx context.Context) (*Mint, error) {
	result, err := pr.Edges.MintOrErr()
	if IsNotLoaded(err) {
		result, err = pr.QueryMint().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (pr *Project) Launchpad(ctx context.Context) (*Launchpad, error) {
	result, err := pr.Edges.LaunchpadOrErr()
	if IsNotLoaded(err) {
		result, err = pr.QueryLaunchpad().Only(ctx)
	}
	return result, MaskNotFound(err)
}
