-- Create "projects" table
CREATE TABLE "projects" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "address" character varying NOT NULL, "slot" bigint NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "value_decimal" bigint NOT NULL, "forecasted_apr" character varying NULL, "total_value" character varying NOT NULL, "payment_token" jsonb NOT NULL, "metadata" jsonb NOT NULL, PRIMARY KEY ("id"));
-- Create index "project_address_slot" to table: "projects"
CREATE UNIQUE INDEX "project_address_slot" ON "projects" ("address", "slot");
-- Create "launchpads" table
CREATE TABLE "launchpads" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "is_ready" boolean NOT NULL DEFAULT false, "minter_contract" jsonb NOT NULL, "whitelisted_sale_open" boolean NOT NULL DEFAULT false, "public_sale_open" boolean NOT NULL DEFAULT false, "is_sold_out" boolean NOT NULL DEFAULT false, "is_canceled" boolean NOT NULL DEFAULT false, "project_launchpad" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "launchpads_projects_launchpad" FOREIGN KEY ("project_launchpad") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "launchpads_project_launchpad_key" to table: "launchpads"
CREATE UNIQUE INDEX "launchpads_project_launchpad_key" ON "launchpads" ("project_launchpad");
-- Create "mints" table
CREATE TABLE "mints" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "min_value_per_tx" character varying NOT NULL, "max_value_per_tx" character varying NOT NULL, "minter_address" character varying NOT NULL, "project_mint" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "mints_projects_mint" FOREIGN KEY ("project_mint") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "mints_project_mint_key" to table: "mints"
CREATE UNIQUE INDEX "mints_project_mint_key" ON "mints" ("project_mint");
