// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Launchpad is the predicate function for launchpad builders.
type Launchpad func(*sql.Selector)

// Mint is the predicate function for mint builders.
type Mint func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)
